// Generated by go-core v1.7.0 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 a3cff83912690bd206370c3cb004ff7e8ffc9326379bb25e27bc6d61c2812556
export type CategorySettings = {
  category: string;
  email: Setting;
};

export type Item = {
  id: number;
  category: string;
  title: string;
  body: string;
  link: string;
  data: Record<string, string>;
  read_at: string | null;
  created_at: string;
};

export type Page = {
  items: Item[];
  has_more: boolean;
};

export type Preferences = {
  email_available: boolean;
  categories: CategorySettings[];
  quiet_hours: QuietHours;
  time_zone: string;
};

export type QuietHours = {
  enabled: boolean;
  start: number;
  end: number;
};

export type Setting = {
  enabled: boolean;
  source: Source;
};

export type Source = "enforced" | "person" | "default";

export type StreamEvent = {
  type: StreamKind;
  notification?: Item | null;
  read_ids?: number[];
  all_read?: boolean;
  read_up_to_id?: number;
  unread_count: number;
};

export type StreamKind = "created" | "read" | "unread";

export type UnreadCount = {
  unread_count: number;
};
