// Generated by go-core v1.7.0-rc.1 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 575375342825549963c2617628d28f69b981ba4b32fd136d723fb42facab6a44
export type Item = {
  id: number;
  category: string;
  title: string;
  body: string;
  link: string;
  data: Record<string, string>;
  read_at: string | null;
  created_at: string;
};

export type Page = {
  items: Item[];
  has_more: boolean;
};

export type StreamEvent = {
  type: StreamKind;
  notification?: Item | null;
  read_ids?: number[];
  all_read?: boolean;
  read_up_to_id?: number;
  unread_count: number;
};

export type StreamKind = "created" | "read" | "unread";

export type UnreadCount = {
  unread_count: number;
};
