// Generated by go-core v1.7.0-rc.1 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 0d589aad2aa9098de77384266335e4d57405c6a198ae085d9be4da7f1e1aca98
import { route } from "../../client";
import type { ListQuery, MarkAllInput, ReadInput } from "./schemas";
import type { Page, UnreadCount } from "./entities";

export const notificationRoutes = {
  list: route<ListQuery, Page>("GET", "/v1/notifications"),
  unread: route<void, UnreadCount>("GET", "/v1/notifications/unread"),
  read: route<ReadInput, UnreadCount>("POST", "/v1/notifications/:id/read"),
  readAll: route<MarkAllInput, UnreadCount>("POST", "/v1/notifications/read"),
  stream: route.raw("GET", "/v1/notifications/stream"),
  test: route<void, void>("POST", "/v1/notifications/test"),
} as const;
