// Generated by go-core v1.7.0-rc.2 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 29137bb48e97da13afd5f32c553d980ce5b1f136b8b5c0d9f137455785c5b7f1
import { route } from "../../client";
import type { ListQuery, MarkAllInput, QuietHoursInput, ReadInput, SetEmailInput } from "./schemas";
import type { CategorySettings, Page, Preferences, QuietHours, UnreadCount } from "./entities";

export const notificationRoutes = {
  list: route<ListQuery, Page>("GET", "/v1/notifications"),
  unread: route<void, UnreadCount>("GET", "/v1/notifications/unread"),
  read: route<ReadInput, UnreadCount>("POST", "/v1/notifications/:id/read"),
  readAll: route<MarkAllInput, UnreadCount>("POST", "/v1/notifications/read"),
  stream: route.raw("GET", "/v1/notifications/stream"),
  test: route<void, void>("POST", "/v1/notifications/test"),
  preferences: route<void, Preferences>("GET", "/v1/notifications/preferences"),
  preferencesSetEmail: route<SetEmailInput, CategorySettings>("PUT", "/v1/notifications/preferences/:category"),
  quietHours: route<QuietHoursInput, QuietHours>("PUT", "/v1/notifications/quiet-hours"),
} as const;
