// Generated by go-core v1.7.0-rc.2 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 8f4cb46243e38ccb50231bb8b4cb26f32650125411f9cf0a62c9b67adc8f0ae1
import { z } from 'zod';

export const ListQuerySchema = z.object({
  before_id: z.number().int().optional(),
  limit: z.number().int().optional(),
});

export type ListQuery = z.infer<typeof ListQuerySchema>;

export const MarkAllInputSchema = z.object({
  up_to_id: z.number().int().min(0),
});

export type MarkAllInput = z.infer<typeof MarkAllInputSchema>;

export const QuietHoursInputSchema = z.object({
  enabled: z.boolean(),
  start: z.number().int().min(0).max(1439),
  end: z.number().int().min(0).max(1439),
});

export type QuietHoursInput = z.infer<typeof QuietHoursInputSchema>;

export const ReadInputSchema = z.object({
  id: z.number().int(),
});

export type ReadInput = z.infer<typeof ReadInputSchema>;

export const SetEmailInputSchema = z.object({
  category: z.string().min(1).max(64),
  email: z.boolean().nullable(),
});

export type SetEmailInput = z.infer<typeof SetEmailInputSchema>;
