// Generated by go-core v1.7.0-rc.1 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 3a753d05e12eb5962df927dd0d1d52b213e056181c7eb0b0b7c2944c1f0022dc
import { z } from 'zod';

export const ListQuerySchema = z.object({
  before_id: z.number().int().optional(),
  limit: z.number().int().optional(),
});

export type ListQuery = z.infer<typeof ListQuerySchema>;

export const MarkAllInputSchema = z.object({
  up_to_id: z.number().int().min(0),
});

export type MarkAllInput = z.infer<typeof MarkAllInputSchema>;

export const ReadInputSchema = z.object({
  id: z.number().int(),
});

export type ReadInput = z.infer<typeof ReadInputSchema>;
