// Generated by go-core v1.7.0-rc.1 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 eb8b24ee7316b345c0f34167eeecb451c0eb6d6104aa9e3126f96d1aa099c1c1
import { route, type ListResult } from "../../client";
import type { ActivityInput, ChangeLocaleInput, ChangePasswordInput, ChangesInput, ConfirmEmailInput, CreateUserInput, ListUsersInput, LoginAsInput, LoginInput, OwnSessionInput, OwnSignInsInput, RefreshInput, RequestEmailInput, SetPasswordInput, SignInsInput, UpdateProfileInput, UpdateUserInput, UserInput, UserSessionInput } from "./schemas";
import type { ActivityRow, ChangeRow, PendingEmail, ProfileResponse, SessionList, SessionResponse, SignInRow, UnlockResult, UserDetail, UserRow } from "./entities";

export const identityRoutes = {
  login: route<LoginInput, SessionResponse>("POST", "/v1/auth/login", { public: true }),
  refresh: route<RefreshInput, SessionResponse>("POST", "/v1/auth/refresh", { public: true }),
  logout: route<void, void>("POST", "/v1/auth/logout"),
  me: route<void, SessionResponse>("GET", "/v1/auth/me"),
  changeLocale: route<ChangeLocaleInput, void>("POST", "/v1/auth/change-locale"),
  loginAs: route<LoginAsInput, SessionResponse>("POST", "/v1/auth/login-as"),
  loginAsReturn: route<void, SessionResponse>("POST", "/v1/auth/login-as/return"),
  usersList: route<ListUsersInput, ListResult<UserRow>>("GET", "/v1/iam/users", { permission: "iam.user:view" }),
  usersShow: route<UserInput, UserDetail>("GET", "/v1/iam/users/:id", { permission: "iam.user:view" }),
  usersCreate: route<CreateUserInput, UserDetail>("POST", "/v1/iam/users", { permission: "iam.user:manage" }),
  usersUpdate: route<UpdateUserInput, UserDetail>("PUT", "/v1/iam/users/:id", { permission: "iam.user:manage" }),
  usersSetPassword: route<SetPasswordInput, void>("PUT", "/v1/iam/users/:id/password", { permission: "iam.user:manage" }),
  usersDeactivate: route<UserInput, void>("POST", "/v1/iam/users/:id/deactivate", { permission: "iam.user:manage" }),
  usersActivate: route<UserInput, void>("POST", "/v1/iam/users/:id/activate", { permission: "iam.user:manage" }),
  usersUnlock: route<UserInput, UnlockResult>("POST", "/v1/iam/users/:id/unlock", { permission: "iam.user:manage" }),
  usersSignins: route<SignInsInput, ListResult<SignInRow>>("GET", "/v1/iam/users/:id/signins", { permission: "iam.user:view" }),
  usersChanges: route<ChangesInput, ListResult<ChangeRow>>("GET", "/v1/iam/users/:id/changes", { permission: "iam.user:view" }),
  usersActivity: route<ActivityInput, ListResult<ActivityRow>>("GET", "/v1/iam/users/:id/activity", { permission: "iam.user.activity:view" }),
  usersSessions: route<UserInput, SessionList>("GET", "/v1/iam/users/:id/sessions", { permission: "iam.user:view" }),
  usersRevokeSession: route<UserSessionInput, void>("DELETE", "/v1/iam/users/:id/sessions/:session_id", { permission: "iam.user:manage" }),
  usersRevokeSessions: route<UserInput, void>("DELETE", "/v1/iam/users/:id/sessions", { permission: "iam.user:manage" }),
  profileShow: route<void, ProfileResponse>("GET", "/v1/iam/profile"),
  profileUpdate: route<UpdateProfileInput, ProfileResponse>("PUT", "/v1/iam/profile"),
  profileChangePassword: route<ChangePasswordInput, void>("PUT", "/v1/iam/profile/password"),
  profileRequestEmail: route<RequestEmailInput, PendingEmail>("POST", "/v1/iam/profile/email"),
  profileResendEmail: route<void, PendingEmail>("POST", "/v1/iam/profile/email/resend"),
  profileConfirmEmail: route<ConfirmEmailInput, ProfileResponse>("POST", "/v1/iam/profile/email/confirm"),
  profileCancelEmail: route<void, void>("DELETE", "/v1/iam/profile/email"),
  profileSignins: route<OwnSignInsInput, ListResult<SignInRow>>("GET", "/v1/iam/profile/signins"),
  profileSessions: route<void, SessionList>("GET", "/v1/iam/profile/sessions"),
  profileRevokeSession: route<OwnSessionInput, void>("DELETE", "/v1/iam/profile/sessions/:session_id"),
} as const;
