// Generated by go-core v1.7.0-rc.1 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 475ca259ffb894da741847405fd45902489b02cec88c5bbdc20ab79eb923cdbc
export type DeadLetterRow = {
  event_id: number;
  consumer: string;
  event_name: string;
  event_created_at: string | null;
  attempts: number;
  last_error: string;
  dead_at: string;
  retryable: boolean;
};

export type Retried = {
  retried: number;
};
