// Generated by go-core v1.7.0-rc.2 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 d79b9141fd3abbb1be887cc74c226a39d234b7580f14219c0ecd98f7bdd03b4f
export type ConsumerNames = {
  consumers: string[];
};

export type DeadLetterRow = {
  event_id: number;
  consumer: string;
  event_name: string;
  event_created_at: string | null;
  attempts: number;
  last_error: string;
  dead_at: string;
  retryable: boolean;
};

export type Retried = {
  retried: number;
};
