// Generated by go-core v1.7.0-rc.1 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 03595989cdbaac7d0b83d191330a716c4ba0673b663812d8cc8eb8bf4590c46c
import { route, type ListResult } from "../../client";
import type { DeadLettersInput, RetryAllInput, RetryInput } from "./schemas";
import type { DeadLetterRow, Retried } from "./entities";

export const eventsRoutes = {
  deadLettersList: route<DeadLettersInput, ListResult<DeadLetterRow>>("GET", "/v1/events/dead-letters", { permission: "events.deadletter:view" }),
  deadLettersRetry: route<RetryInput, Retried>("POST", "/v1/events/dead-letters/:event/:consumer/retry", { permission: "events.deadletter:retry" }),
  deadLettersRetryAll: route<RetryAllInput, Retried>("POST", "/v1/events/dead-letters/retry", { permission: "events.deadletter:retry" }),
} as const;
