// Generated by go-core v1.7.0-rc.2 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 53b8b40cc65526cb9a001a84a4e79ab62416d886805f90b594af01bd1ceae49f
import { route, type ListResult } from "../../client";
import type { DeadLettersInput, RetryAllInput, RetryInput } from "./schemas";
import type { ConsumerNames, DeadLetterRow, Retried } from "./entities";

export const eventsRoutes = {
  deadLettersList: route<DeadLettersInput, ListResult<DeadLetterRow>>("GET", "/v1/events/dead-letters", { permission: "events.deadletter:view" }),
  deadLettersRetry: route<RetryInput, Retried>("POST", "/v1/events/dead-letters/:event/:consumer/retry", { permission: "events.deadletter:retry" }),
  deadLettersRetryAll: route<RetryAllInput, Retried>("POST", "/v1/events/dead-letters/retry", { permission: "events.deadletter:retry" }),
  consumers: route<void, ConsumerNames>("GET", "/v1/events/consumers", { permission: "events.deadletter:view" }),
} as const;
