// Generated by go-core v1.7.0 (cmd/modulets); do not edit: npm run modules:sync.
// sha256 0ca8f8a6f070799278421c7aeffab1e1bba32184c94c09243acf6f34b3f373d5
import { z } from 'zod';

export const DeadLettersInputSchema = z.object({
  consumer: z.string().max(100).optional(),
  page: z.number().int().optional(),
  per_page: z.number().int().optional(),
});

export type DeadLettersInput = z.infer<typeof DeadLettersInputSchema>;

export const RetryAllInputSchema = z.object({
  consumer: z.string().min(1).max(100),
});

export type RetryAllInput = z.infer<typeof RetryAllInputSchema>;

export const RetryInputSchema = z.object({
  event: z.number().int().refine((n) => n !== 0, { params: { code: 'required' } }),
  consumer: z.string().min(1).max(100),
});

export type RetryInput = z.infer<typeof RetryInputSchema>;
