// go-core's module contracts (identity, access) are committed under src/modules/<module>/.
//
//   npm run modules:sync -- <path to a go-core checkout at the version in package.json "goCore">
//   npm run check:modules          (part of `npm run check`)
//
// sync runs `go run ./cmd/modulets` in the checkout and writes the files with two header lines: the go-core
// version that wrote them and a hash of their content. check fails when a file's version differs from
// package.json or its content no longer matches its hash (someone edited it by hand).
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "src", "modules");
const { goCore } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const hashOf = (body) => createHash("sha256").update(body).digest("hex");
const header = (hash) =>
  `// Generated by go-core ${goCore} (cmd/modulets); do not edit: npm run modules:sync.\n// sha256 ${hash}\n`;

function* files(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* files(path);
    else if (entry.name.endsWith(".ts")) yield path;
  }
}

function sync(checkout) {
  if (!checkout) throw new Error("usage: npm run modules:sync -- <path to the go-core checkout>");
  const tag = execFileSync("git", ["describe", "--tags", "--exact-match"], { cwd: checkout, encoding: "utf8" }).trim();
  if (tag !== goCore) throw new Error(`the checkout is at ${tag}, package.json "goCore" says ${goCore}`);

  const out = mkdtempSync(join(tmpdir(), "modulets-"));
  try {
    execFileSync("go", ["run", "./cmd/modulets", out], { cwd: checkout, stdio: "inherit" });
    rmSync(target, { recursive: true, force: true });
    for (const file of files(out)) {
      const body = readFileSync(file, "utf8")
        .split("\n")
        .slice(1) // go-core's own header names "devel" when it runs inside its checkout
        .join("\n")
        // src/ reaches the library by relative path, never by its package name
        .replaceAll('from "@wssto2/vue-core/client"', 'from "../../client"');
      const destination = join(target, file.slice(out.length + 1));
      mkdirSync(dirname(destination), { recursive: true });
      writeFileSync(destination, header(hashOf(body)) + body);
    }
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
  console.log(`src/modules written from go-core ${goCore}`);
}

function check() {
  const problems = [];
  const names = [...files(target)];
  if (names.length === 0) problems.push("src/modules is empty: run npm run modules:sync");
  for (const file of names) {
    const [first = "", second = "", ...rest] = readFileSync(file, "utf8").split("\n");
    const at = file.slice(root.length + 1);
    if (!first.startsWith(`// Generated by go-core ${goCore} `)) problems.push(`${at}: written by another go-core version than ${goCore}`);
    else if (second !== `// sha256 ${hashOf(rest.join("\n"))}`) problems.push(`${at}: edited by hand; run npm run modules:sync`);
  }
  if (problems.length > 0) {
    console.error(`module types out of date:\n  ${problems.join("\n  ")}`);
    process.exit(1);
  }
  console.log(`src/modules: ${names.length} files, all from go-core ${goCore}`);
}

if (process.argv[2] === "sync") sync(process.argv[3]);
else if (process.argv[2] === "check") check();
else throw new Error("usage: node scripts/modules.mjs sync <checkout> | check");
