// This file is auto-generated by go-core v0.0.0-test. Do not edit manually.
import { route } from "@wssto2/vue-core/client";
import type { Draft, ListInput, ShowInput } from "./schemas";
import type { Row, Ticket } from "./entities";

export const ticketsRoutes = {
  getTickets: route<ListInput, Row[]>("GET", "/tickets"),
  show: route<ShowInput, Ticket>("GET", "/tickets/:id", { permission: "tickets.ticket:view" }),
  create: route<Draft, Ticket>("POST", "/tickets", { permission: "tickets.ticket:manage" }),
  deleteTicketsById: route<ShowInput, void>("DELETE", "/tickets/:id"),
  postTicketsByIdSendOrder: route<ShowInput, void>("POST", "/tickets/:id/send-order"),
  getHealth: route<void, string>("GET", "/health", { public: true }),
  getEvents: route.raw("GET", "/events", { public: true }),
  getExport: route.raw("GET", "/export", { permission: "tickets.ticket:view" }),
} as const;
