// This file is auto-generated by go-core v0.0.0-test. Do not edit manually.
import { z } from 'zod';

export const PersonSchema = z.object({
  id: z.number().int(),
  name: z.string(),
});

export type Person = z.infer<typeof PersonSchema>;

export const DraftSchema = z.object({
  title: z.string().min(1).max(100),
  owner: PersonSchema,
});

export type Draft = z.infer<typeof DraftSchema>;

export const ListInputSchema = z.object({
  status: z.string().max(20),
  page: z.number().int(),
});

export type ListInput = z.infer<typeof ListInputSchema>;

export const ShowInputSchema = z.object({
  id: z.number().int(),
});

export type ShowInput = z.infer<typeof ShowInputSchema>;
